spring.application.name=Spring Boot Batch
# Spring Boot
server.port=8585

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5444/devdb
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# Show SQL queries
spring.jpa.show-sql=true
# Format SQL queries
spring.jpa.properties.hibernate.format_sql=true

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html


